import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import FontAwesomeConfig from "./fontawesome";
import localFont from "next/font/local";

const satoshi = localFont({
  src:"../font/Satoshi-Variable.ttf", 
  variable: "--satoshi"
})

const integral = localFont({
  src:"../font/Integral CF Regular.ttf", 
  variable: "--integral"
})



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <FontAwesomeConfig />
      </head>
      <body className={(inter.className, satoshi.variable, integral.variable )}>{children}</body>
    </html>
  );
}
